[build]
  command = "npm ci --include=dev && npm run build"
  publish = "out"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

# Handle Next.js static export routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Redirect /home to root
[[redirects]]
  from = "/home"
  to = "/"
  status = 301

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "public, max-age=3600, stale-while-revalidate=86400"

# Environment variables should be set in Netlify dashboard:
# - Go to Site settings → Environment variables
# - Set the following variables with actual values:
#
# NODE_ENV = production
# NEXT_PUBLIC_SUPABASE_URL = [Your Supabase project URL]
# NEXT_PUBLIC_SUPABASE_ANON_KEY = [Your Supabase anon key]
# NEXT_PUBLIC_SITE_URL = [Your Netlify site URL]
# NEXT_PUBLIC_GA_ID = [Your Google Analytics ID] 